name: zammad-nolocaldb
description: zammad-nolocaldb
cli: false
notifications: false
default_dependencies: false
buildpack: https://github.com/heroku/heroku-buildpack-hello.git#master
targets:
  centos-6:
  centos-7:
  debian-8:
  ubuntu-16.04:
